package com.ossovita.commonservice.enums;

public enum NotificationType {
    CUSTOMER_WELCOME_NOTIFICATION,
    RESERVATION_BOOKED_NOTIFICATION,
    CHECK_IN_NOTIFICATION,
    CHECK_OUT_NOTIFICATION,
    RESERVATION_PAYMENT_REFUND_NOTIFICATION
}
